feat: add `@uploadcare/signed-uploads` package containing helper to generate signature for signed uploads
uploadcare/uploadcare-js-api-clients pull request #466
Opened 2023-03-08 17:40 UTC by nd0ut

2023-03-08 21:22 UTC, rsedykh requested changes

2023-03-08 21:22 UTC, rsedykh commented on packages/signed-uploads/README.md
> +This is an Uploadcare [Signed Uploads][uc-docs-signed-uploads] wrapper to work with
```suggestion
This is Uploadcare [Signed Uploads][uc-docs-signed-uploads] wrapper to work with
```

2023-03-08 21:22 UTC, rsedykh commented on packages/signed-uploads/README.md
> +[![GitHub release][badge-release-img]][badge-release-url]&nbsp;
```suggestion
[![GitHub release][badge-release-img]][badge-release-url]
```
?

2023-03-09 11:30 UTC, nd0ut commented
Checks are failed because of prettier that wants to format all the jsdoc comments. I'll fix it right before merge to keep diff clean.

2023-03-09 12:02 UTC, dmitry-mukhin approved these changes

2023-03-09 12:12 UTC, rsedykh approved these changes

2023-03-09 12:47 UTC, merged